In [ ]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
from yaml import safe_load
import pickle

In [ ]:
filenames = []
for file in os.listdir('t20s'):
    filenames.append(os.path.join('t20s', file))

In [ ]:
print(filenames)

In [ ]:
final_df = pd.DataFrame()
cnt = 1
error_terms = 0
for file in tqdm(filenames):
    with open(file, 'r') as f:
        try:
            df = pd.json_normalize(safe_load(f))
        except:
            error_terms += 1
            continue
        df['match_id'] = cnt
        final_df = pd.concat([final_df, df], ignore_index=True)
        cnt+=1

In [ ]:
backup_df = final_df.copy()

In [34]:
backup_df.to_csv("initialData.csv")

In [ ]:
# Filtering to account for Men's matches only as there is more data
final_df = final_df[final_df['info.gender'] == 'male']

In [ ]:
# Deleting unnecessary columns
final_df.drop(columns=['meta.data_version', 
                       'meta.created',
                       'meta.revision',
                       'info.gender',
                       'info.player_of_match',
                       'info.umpires',
                       'info.bowl_out',
                       'info.outcome.bowl_out',
                       'info.supersubs.New Zealand',
                       'info.supersubs.South Africa',
                       'info.outcome.winner',
                       'info.outcome.by.wickets',
                       'info.neutral_venue',
                       'info.outcome.by.runs',
                      'info.outcome.method',
                      'info.outcome.eliminator',
                      'info.outcome.result',
                      'info.match_type_number',
                      'info.outcome.by.wickets'], inplace=True)

In [ ]:
# for col in final_df.columns:
#     print(col)

In [31]:
final_df = final_df[final_df['info.overs'] == 20]
final_df.drop(columns=['info.overs',
                       'info.match_type'], inplace=True)

In [32]:
final_df

,innings,info.city,info.dates,info.teams,info.toss.decision,info.toss.winner,info.venue,match_id
2,"[{'1st innings': {'team': 'West Indies', 'deli...",Lauderhill,[2019-08-03],"[India, West Indies]",field,India,Central Broward Regional Park Stadium Turf Ground,3
3,"[{'1st innings': {'team': 'West Indies', 'deli...",St Lucia,[2012-03-27],"[West Indies, Australia]",bat,West Indies,"Beausejour Stadium, Gros Islet",4
4,"[{'1st innings': {'team': 'India', 'deliveries...",Bangalore,[2017-02-01],"[India, England]",field,England,M Chinnaswamy Stadium,5
5,"[{'1st innings': {'team': 'England', 'deliveri...",Nottingham,[2009-06-11],"[England, South Africa]",bat,England,Trent Bridge,6
6,"[{'1st innings': {'team': 'South Africa', 'del...",Cape Town,[2020-12-01],"[South Africa, England]",bat,South Africa,Newlands,7
...,...,...,...,...,...,...,...,...
1423,"[{'1st innings': {'team': 'Hong Kong', 'delive...",Abu Dhabi,[2017-01-16],"[Hong Kong, Oman]",field,Oman,Sheikh Zayed Stadium,1424
1424,"[{'1st innings': {'team': 'Maldives', 'deliver...",Kuala Lumpur,[2019-06-29],"[Maldives, Thailand]",field,Thailand,Kinrara Academy Oval,1425
1427,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Chattogram,[2019-09-20],"[Afghanistan, Zimbabwe]",bat,Afghanistan,Zahur Ahmed Chowdhury Stadium,1428
1429,"[{'1st innings': {'team': 'Canada', 'deliverie...",Hamilton,[2019-08-25],"[Canada, United States of America]",field,United States of America,"White Hill Field, Sandys Parish",1430
1430,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Auckland,[2020-12-18],"[Pakistan, New Zealand]",bat,Pakistan,Eden Park,1431

In [33]:
pickle.dump(final_df, open("dataset_lvl1.pkl", 'wb'))